-- 인천서비스PCELL성연령인구(PCELL) | Postrgres | INCHEON_SERVICE_PCELL_SEX_AGE_POP

CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP (
	std_ymd VARCHAR(8),
	hcode VARCHAR(10),
	x_coord DECIMAL(18, 8),
	y_coord DECIMAL(18, 8),
	h_m_10 DECIMAL(18, 2),
	h_m_20 DECIMAL(18, 2),
	h_m_30 DECIMAL(18, 2),
	h_m_40 DECIMAL(18, 2),
	h_m_50 DECIMAL(18, 2),
	h_m_60 DECIMAL(18, 2),
	h_m_70 DECIMAL(18, 2),
	h_w_10 DECIMAL(18, 2),
	h_w_20 DECIMAL(18, 2),
	h_w_30 DECIMAL(18, 2),
	h_w_40 DECIMAL(18, 2),
	h_w_50 DECIMAL(18, 2),
	h_w_60 DECIMAL(18, 2),
	h_w_70 DECIMAL(18, 2),
	w_m_10 DECIMAL(18, 2),
	w_m_20 DECIMAL(18, 2),
	w_m_30 DECIMAL(18, 2),
	w_m_40 DECIMAL(18, 2),
	w_m_50 DECIMAL(18, 2),
	w_m_60 DECIMAL(18, 2),
	w_m_70 DECIMAL(18, 2),
	w_w_10 DECIMAL(18, 2),
	w_w_20 DECIMAL(18, 2),
	w_w_30 DECIMAL(18, 2),
	w_w_40 DECIMAL(18, 2),
	w_w_50 DECIMAL(18, 2),
	w_w_60 DECIMAL(18, 2),
	w_w_70 DECIMAL(18, 2),
	v_m_10 DECIMAL(18, 2),
	v_m_20 DECIMAL(18, 2),
	v_m_30 DECIMAL(18, 2),
	v_m_40 DECIMAL(18, 2),
	v_m_50 DECIMAL(18, 2),
	v_m_60 DECIMAL(18, 2),
	v_m_70 DECIMAL(18, 2),
	v_w_10 DECIMAL(18, 2),
	v_w_20 DECIMAL(18, 2),
	v_w_30 DECIMAL(18, 2),
	v_w_40 DECIMAL(18, 2),
	v_w_50 DECIMAL(18, 2),
	v_w_60 DECIMAL(18, 2),
	v_w_70 DECIMAL(18, 2),
	block_cd VARCHAR(20)
) PARTITION BY RANGE (std_ymd);


COMMENT ON TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP IS '인천서비스PCELL성연령인구(PCELL)';

COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.std_ymd IS '기준일자';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.hcode IS '행정동코드';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.x_coord IS 'X좌표';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.y_coord IS 'Y좌표';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_m_10 IS '주거인구 남자 10대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_m_20 IS '주거인구 남자 20대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_m_30 IS '주거인구 남자 30대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_m_40 IS '주거인구 남자 40대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_m_50 IS '주거인구 남자 50대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_m_60 IS '주거인구 남자 60대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_m_70 IS '주거인구 남자 70대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_w_10 IS '주거인구 여자 10대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_w_20 IS '주거인구 여자 20대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_w_30 IS '주거인구 여자 30대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_w_40 IS '주거인구 여자 40대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_w_50 IS '주거인구 여자 50대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_w_60 IS '주거인구 여자 60대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.h_w_70 IS '주거인구 여자 70대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_m_10 IS '직장인구 남자 10대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_m_20 IS '직장인구 남자 20대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_m_30 IS '직장인구 남자 30대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_m_40 IS '직장인구 남자 40대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_m_50 IS '직장인구 남자 50대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_m_60 IS '직장인구 남자 60대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_m_70 IS '직장인구 남자 70대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_w_10 IS '직장인구 여자 10대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_w_20 IS '직장인구 여자 20대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_w_30 IS '직장인구 여자 30대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_w_40 IS '직장인구 여자 40대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_w_50 IS '직장인구 여자 50대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_w_60 IS '직장인구 여자 60대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.w_w_70 IS '직장인구 여자 70대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_m_10 IS '방문인구 남자 10대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_m_20 IS '방문인구 남자 20대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_m_30 IS '방문인구 남자 30대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_m_40 IS '방문인구 남자 40대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_m_50 IS '방문인구 남자 50대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_m_60 IS '방문인구 남자 60대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_m_70 IS '방문인구 남자 70대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_w_10 IS '방문인구 여자 10대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_w_20 IS '방문인구 여자 20대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_w_30 IS '방문인구 여자 30대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_w_40 IS '방문인구 여자 40대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_w_50 IS '방문인구 여자 50대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_w_60 IS '방문인구 여자 60대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.v_w_70 IS '방문인구 여자 70대';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP.block_cd IS '소지역코드';


CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_01 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20220101') TO ('20220201');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_02 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20220201') TO ('20220301');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_03 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20220301') TO ('20220401');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_04 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20220401') TO ('20220501');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_05 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20220501') TO ('20220601');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_06 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20220601') TO ('20220701');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_07 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20220701') TO ('20220801');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_08 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20220801') TO ('20220901');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_09 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20220901') TO ('20221001');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_10 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20221001') TO ('20221101');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_11 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20221101') TO ('20221201');
CREATE TABLE ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP_2022_12 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_SEX_AGE_POP FOR VALUES FROM ('20221201') TO ('20220101');