-- 지구대정보 | PLBX_INFO

CREATE EXTERNAL TABLE IF NOT EXISTS SOSS.PLBX_INFO (
	plbx_nm STRING COMMENT '지구대명@pk',
	plbx_adrs STRING COMMENT '지구대주소',
	plst_nm STRING COMMENT '경찰서명',
	gu_cd STRING COMMENT '구코드',
	la DECIMAL(18,8) COMMENT '위도',
	lo DECIMAL(18,8) COMMENT '경도'
)
COMMENT '지구대정보'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY "|"
STORED AS TEXTFILE 
LOCATION 'maprfs:/DM/soss.db/PLBX_INFO'
;