-- 인천서비스PCELL시간인구(PCELL) | Postgres | INCHEON_SERVICE_PCELL_TIME_POP

CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP (
	std_ymd VARCHAR(8)
, hcode VARCHAR(10)
, x_coord DECIMAL(18, 8)
, y_coord DECIMAL(18, 8)
, h_t_00 DECIMAL(18, 2)
, h_t_01 DECIMAL(18, 2)
, h_t_02 DECIMAL(18, 2)
, h_t_03 DECIMAL(18, 2)
, h_t_04 DECIMAL(18, 2)
, h_t_05 DECIMAL(18, 2)
, h_t_06 DECIMAL(18, 2)
, h_t_07 DECIMAL(18, 2)
, h_t_08 DECIMAL(18, 2)
, h_t_09 DECIMAL(18, 2)
, h_t_10 DECIMAL(18, 2)
, h_t_11 DECIMAL(18, 2)
, h_t_12 DECIMAL(18, 2)
, h_t_13 DECIMAL(18, 2)
, h_t_14 DECIMAL(18, 2)
, h_t_15 DECIMAL(18, 2)
, h_t_16 DECIMAL(18, 2)
, h_t_17 DECIMAL(18, 2)
, h_t_18 DECIMAL(18, 2)
, h_t_19 DECIMAL(18, 2)
, h_t_20 DECIMAL(18, 2)
, h_t_21 DECIMAL(18, 2)
, h_t_22 DECIMAL(18, 2)
, h_t_23 DECIMAL(18, 2)
, w_t_00 DECIMAL(18, 2)
, w_t_01 DECIMAL(18, 2)
, w_t_02 DECIMAL(18, 2)
, w_t_03 DECIMAL(18, 2)
, w_t_04 DECIMAL(18, 2)
, w_t_05 DECIMAL(18, 2)
, w_t_06 DECIMAL(18, 2)
, w_t_07 DECIMAL(18, 2)
, w_t_08 DECIMAL(18, 2)
, w_t_09 DECIMAL(18, 2)
, w_t_10 DECIMAL(18, 2)
, w_t_11 DECIMAL(18, 2)
, w_t_12 DECIMAL(18, 2)
, w_t_13 DECIMAL(18, 2)
, w_t_14 DECIMAL(18, 2)
, w_t_15 DECIMAL(18, 2)
, w_t_16 DECIMAL(18, 2)
, w_t_17 DECIMAL(18, 2)
, w_t_18 DECIMAL(18, 2)
, w_t_19 DECIMAL(18, 2)
, w_t_20 DECIMAL(18, 2)
, w_t_21 DECIMAL(18, 2)
, w_t_22 DECIMAL(18, 2)
, w_t_23 DECIMAL(18, 2)
, v_t_00 DECIMAL(18, 2)
, v_t_01 DECIMAL(18, 2)
, v_t_02 DECIMAL(18, 2)
, v_t_03 DECIMAL(18, 2)
, v_t_04 DECIMAL(18, 2)
, v_t_05 DECIMAL(18, 2)
, v_t_06 DECIMAL(18, 2)
, v_t_07 DECIMAL(18, 2)
, v_t_08 DECIMAL(18, 2)
, v_t_09 DECIMAL(18, 2)
, v_t_10 DECIMAL(18, 2)
, v_t_11 DECIMAL(18, 2)
, v_t_12 DECIMAL(18, 2)
, v_t_13 DECIMAL(18, 2)
, v_t_14 DECIMAL(18, 2)
, v_t_15 DECIMAL(18, 2)
, v_t_16 DECIMAL(18, 2)
, v_t_17 DECIMAL(18, 2)
, v_t_18 DECIMAL(18, 2)
, v_t_19 DECIMAL(18, 2)
, v_t_20 DECIMAL(18, 2)
, v_t_21 DECIMAL(18, 2)
, v_t_22 DECIMAL(18, 2)
, v_t_23 DECIMAL(18, 2)
, block_cd VARCHAR(20)
) PARTITION BY RANGE (std_ymd);

-- 테이블 COMMENT
COMMENT ON TABLE ADHC.INCHEON_SERVICE_PCELL_TIME_POP IS '인천서비스PCELL시간인구(PCELL)';

-- 컬럼 COMMENT
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.std_ymd IS '기준일자';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.hcode IS '행정동코드';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.x_coord IS 'X좌표';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.y_coord IS 'Y좌표';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_00 IS '주거인구00시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_01 IS '주거인구01시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_02 IS '주거인구02시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_03 IS '주거인구03시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_04 IS '주거인구04시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_05 IS '주거인구05시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_06 IS '주거인구06시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_07 IS '주거인구07시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_08 IS '주거인구08시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_09 IS '주거인구09시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_10 IS '주거인구10시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_11 IS '주거인구11시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_12 IS '주거인구12시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_13 IS '주거인구13시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_14 IS '주거인구14시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_15 IS '주거인구15시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_16 IS '주거인구16시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_17 IS '주거인구17시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_18 IS '주거인구18시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_19 IS '주거인구19시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_20 IS '주거인구20시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_21 IS '주거인구21시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_22 IS '주거인구22시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.h_t_23 IS '주거인구23시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_00 IS '직장인구00시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_01 IS '직장인구01시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_02 IS '직장인구02시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_03 IS '직장인구03시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_04 IS '직장인구04시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_05 IS '직장인구05시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_06 IS '직장인구06시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_07 IS '직장인구07시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_08 IS '직장인구08시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_09 IS '직장인구09시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_10 IS '직장인구10시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_11 IS '직장인구11시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_12 IS '직장인구12시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_13 IS '직장인구13시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_14 IS '직장인구14시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_15 IS '직장인구15시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_16 IS '직장인구16시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_17 IS '직장인구17시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_18 IS '직장인구18시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_19 IS '직장인구19시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_20 IS '직장인구20시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_21 IS '직장인구21시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_22 IS '직장인구22시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.w_t_23 IS '직장인구23시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_00 IS '방문인구00시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_01 IS '방문인구01시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_02 IS '방문인구02시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_03 IS '방문인구03시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_04 IS '방문인구04시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_05 IS '방문인구05시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_06 IS '방문인구06시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_07 IS '방문인구07시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_08 IS '방문인구08시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_09 IS '방문인구09시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_10 IS '방문인구10시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_11 IS '방문인구11시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_12 IS '방문인구12시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_13 IS '방문인구13시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_14 IS '방문인구14시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_15 IS '방문인구15시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_16 IS '방문인구16시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_17 IS '방문인구17시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_18 IS '방문인구18시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_19 IS '방문인구19시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_20 IS '방문인구20시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_21 IS '방문인구21시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_22 IS '방문인구22시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.v_t_23 IS '방문인구23시';
COMMENT ON COLUMN ADHC.INCHEON_SERVICE_PCELL_TIME_POP.block_cd IS '소지역코드';

-- 월별 파티션 컬럼
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_01 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20220101') TO ('20220201');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_02 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20220201') TO ('20220301');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_03 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20220301') TO ('20220401');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_04 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20220401') TO ('20220501');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_05 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20220501') TO ('20220601');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_06 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20220601') TO ('20220701');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_07 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20220701') TO ('20220801');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_08 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20220801') TO ('20220901');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_09 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20220901') TO ('20221001');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_10 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20221001') TO ('20221101');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_11 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20221101') TO ('20221201');
CREATE TABLE IF NOT EXISTS ADHC.INCHEON_SERVICE_PCELL_TIME_POP_2022_12 PARTITION OF ADHC.INCHEON_SERVICE_PCELL_TIME_POP FOR VALUES FROM ('20221201') TO ('20230101');