-- 행정동지구대매핑 | ADMD_PLBX_MAPN

CREATE TABLE IF NOT EXISTS SOSS.ADMD_PLBX_MAPN (
	admd_cd VARCHAR(10) PRIMARY KEY
, gu_cd VARCHAR(5)
, gu_nm VARCHAR(10)
, admd_nm VARCHAR(10)
, plst_nm VARCHAR(10)
, plbx_nm VARCHAR(10)
, plbx_adrs VARCHAR(50)
, ptr_vhcl_co SMALLINT 
);

-- 테이블 COMMENT
COMMENT ON TABLE SOSS.ADMD_PLBX_MAPN IS '행정동지구대매핑';

-- 컬럼 COMMENT
COMMENT ON COLUMN SOSS.ADMD_PLBX_MAPN.admd_cd IS '행정동코드@pk';
COMMENT ON COLUMN SOSS.ADMD_PLBX_MAPN.gu_cd IS '구코드';
COMMENT ON COLUMN SOSS.ADMD_PLBX_MAPN.gu_nm IS '구명';
COMMENT ON COLUMN SOSS.ADMD_PLBX_MAPN.admd_nm IS '경찰서명';
COMMENT ON COLUMN SOSS.ADMD_PLBX_MAPN.plst_nm IS '지구대명';
COMMENT ON COLUMN SOSS.ADMD_PLBX_MAPN.plbx_adrs IS '지구대주소';
COMMENT ON COLUMN SOSS.ADMD_PLBX_MAPN.ptr_vhcl_co IS '순찰차량수';