-- (T)대구날씨예보
CREATE TABLE IF NOT EXISTS SOSS.DG_WTH_FRCS (
	stdr_de VARCHAR(8)
, tmzn VARCHAR(2)
, admd_cd VARCHAR(10)
, admd VARCHAR(10)
, prc_prb VARCHAR(5)
, hd_val VARCHAR(5)
, pbmr_val VARCHAR(5)
, prc_qy VARCHAR(5)
, tmp_val VARCHAR(5)
);

-- 테이블 COMMENT
COMMENT ON TABLE SOSS.DG_WTH_FRCS IS '대구날씨예보';

-- 컬럼 COMMENT
COMMENT ON COLUMN SOSS.DG_WTH_FRCS.stdr_de IS '기준일자';
COMMENT ON COLUMN SOSS.DG_WTH_FRCS.tmzn IS '시간대';
COMMENT ON COLUMN SOSS.DG_WTH_FRCS.admd_cd IS '행정동코드';
COMMENT ON COLUMN SOSS.DG_WTH_FRCS.admd IS '행정동';
COMMENT ON COLUMN SOSS.DG_WTH_FRCS.prc_prb IS '강수확률';
COMMENT ON COLUMN SOSS.DG_WTH_FRCS.hd_val IS '습도값';
COMMENT ON COLUMN SOSS.DG_WTH_FRCS.pbmr_val IS '풍속값';
COMMENT ON COLUMN SOSS.DG_WTH_FRCS.prc_qy IS '강수량';
COMMENT ON COLUMN SOSS.DG_WTH_FRCS.tmp_val IS '기온값';