-- (T)CCTV효율지수그리드
CREATE TABLE IF NOT EXISTS SOSS.DM_CCTV_EFF_IDEX_GRID (
	stdr_de VARCHAR(8)
, stdr_tm VARCHAR(2)
, grid_id VARCHAR(10)
, gu_cd VARCHAR(5) NOT NULL
, admd_cd VARCHAR(10) NOT NULL
, cctv_eff_idex DECIMAL(5, 2) NOT NULL
, need_cctv_co SMALLINT NOT NULL
, CONSTRAINT dm_cctv_eff_idex_grid_pk PRIMARY KEY (stdr_de, stdr_tm, grid_id)
);

-- 테이블 COMMENT
COMMENT ON TABLE SOSS.DM_CCTV_EFF_IDEX_GRID IS 'CCTV효율지수그리드';

-- 컬럼 COMMENT
COMMENT ON COLUMN SOSS.DM_CCTV_EFF_IDEX_GRID.stdr_de IS '기준일자@pk';
COMMENT ON COLUMN SOSS.DM_CCTV_EFF_IDEX_GRID.stdr_tm IS '기준시간@pk';
COMMENT ON COLUMN SOSS.DM_CCTV_EFF_IDEX_GRID.grid_id IS '그리드ID@pk';
COMMENT ON COLUMN SOSS.DM_CCTV_EFF_IDEX_GRID.gu_cd IS '구코드';
COMMENT ON COLUMN SOSS.DM_CCTV_EFF_IDEX_GRID.admd_cd IS '행정동코드';
COMMENT ON COLUMN SOSS.DM_CCTV_EFF_IDEX_GRID.cctv_eff_idex IS 'CCTV효율지수';
COMMENT ON COLUMN SOSS.DM_CCTV_EFF_IDEX_GRID.need_cctv_co IS '필요CCTV수';