-- (T)구별CCTV모니터비율
CREATE TABLE IF NOT EXISTS SOSS.DM_GU_CCTV_MNTR_RATE (
	stdr_de VARCHAR(8) NOT NULL
, gu_cd VARCHAR(5) NOT NULL
, admd_cd VARCHAR(10) NOT NULL
, cctv_tmzn_cd VARCHAR(2) NOT NULL
, mntr_rate DECIMAL(5, 2) NOT NULL
);

-- 테이블 COMMENT
COMMENT ON TABLE SOSS.DM_GU_CCTV_MNTR_RATE IS '구별CCTV모니터비율';

-- 컬럼 COMMENT
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_RATE.stdr_de IS '기준일자';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_RATE.gu_cd IS '구코드';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_RATE.admd_cd IS '행정동코드';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_RATE.cctv_tmzn_cd IS 'CCTV시간대코드';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_RATE.mntr_rate IS '모니터비율';

