-- (T)구별CCTV모니터시간
CREATE TABLE IF NOT EXISTS SOSS.DM_GU_CCTV_MNTR_TM (
	stdr_de VARCHAR(8) NOT NULL
, stdr_tm VARCHAR(2) NOT NULL
, gu_cd VARCHAR(5) NOT NULL
, admd_cd VARCHAR(10) NOT NULL
, cctv_tmzn_cd VARCHAR(10) NOT NULL
, mntr_rate DECIMAL(5, 2) NOT NULL
, cnc_mntr_tm_yn VARCHAR(10) NOT NULL
);

-- 테이블 COMMENT
COMMENT ON TABLE SOSS.DM_GU_CCTV_MNTR_TM IS '구별CCTV모니터시간';

-- 컬럼 COMMENT
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_TM.stdr_de IS '기준일자';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_TM.stdr_tm IS '기준시간';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_TM.gu_cd IS '구코드';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_TM.admd_cd IS '행정동코드';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_TM.cctv_tmzn_cd IS 'CCTV시간대코드';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_TM.mntr_rate IS '모니터비율';
COMMENT ON COLUMN SOSS.DM_GU_CCTV_MNTR_TM.cnc_mntr_tm_yn IS '집중모니터시간여부';

