-- 인천PCELL기준정보 | IC_PCEL_STDR_INFO

CREATE TABLE IF NOT EXISTS SOSS.IC_PCEL_STDR_INFO (
	grid_id VARCHAR(10) PRIMARY KEY,
	mtr_no VARCHAR(10),
	admd_cd VARCHAR(10),
	la DECIMAL(12, 10),
	lo DECIMAL(13, 10),
	utmk_cnt_la DECIMAL(32, 6),
	utmk_cnt_lo DECIMAL(32, 6),
	utmk_min_la DECIMAL(32, 6),
	utmk_min_lo DECIMAL(32, 6),
	utmk_max_la DECIMAL(32, 6),
	utmk_max_lo DECIMAL(32, 6),
	cctv_co SMALLINT
);

-- 테이블 COMMENT
COMMENT ON TABLE SOSS.IC_PCEL_STDR_INFO IS '인천PCELL기준정보';

-- 컬럼 COMMENT
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.grid_id IS '그리드ID@pk';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.mtr_no IS '행렬번호';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.admd_cd IS '행정동코드';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.la IS '위도';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.lo IS '경도';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.utmk_cnt_la IS '중심위도(UTM-K)';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.utmk_cnt_lo IS '중심경도(UTM-K)';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.utmk_min_la IS '최소위도(UTM-K)';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.utmk_min_lo IS '최소경도(UTM-K)';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.utmk_max_la IS '최대위도(UTM-K)';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.utmk_max_lo IS '최대경도(UTM-K)';
COMMENT ON COLUMN SOSS.IC_PCEL_STDR_INFO.cctv_co IS 'CCTV수';