-- 인천날씨예보 | IC_WTH_FRCS

CREATE TABLE IF NOT EXISTS SOSS.IC_WTH_FRCS (
	stdr_de VARCHAR(8) NOT NULL,
	tmzn VARCHAR(2) NOT NULL,
	admd_cd VARCHAR(10) NOT NULL,
	admd VARCHAR(10),
	hd_val VARCHAR(10),
	tmp_val VARCHAR(10)
);

-- 테이블 COMMENT
COMMENT ON TABLE SOSS.IC_WTH_FRCS IS '인천날씨예보';

-- 컬럼 COMMENT
COMMENT ON COLUMN SOSS.IC_WTH_FRCS.stdr_de IS '기준일자';
COMMENT ON COLUMN SOSS.IC_WTH_FRCS.tmzn IS '시간대';
COMMENT ON COLUMN SOSS.IC_WTH_FRCS.admd_cd IS '행정동코드';
COMMENT ON COLUMN SOSS.IC_WTH_FRCS.admd IS '행정동';
COMMENT ON COLUMN SOSS.IC_WTH_FRCS.hd_val IS '습도값';
COMMENT ON COLUMN SOSS.IC_WTH_FRCS.tmp_val IS '기온값';