-- 지구대정보 | PLBX_INFO

CREATE TABLE IF NOT EXISTS SOSS.PLBX_INFO (
	plbx_nm VARCHAR(20) PRIMARY KEY
, plbx_adrs VARCHAR(20) NOT NULL
, plst_nm VARCHAR(10) NOT NULL
, gu_cd VARCHAR(5) NOT NULL
, la DECIMAL(12, 10)
, lo DECIMAL(13, 10)
);

-- 테이블 COMMENT
COMMENT ON COLUMN SOSS.PLBX_INFO IS '지구대정보';

-- 컬럼 COMMENT
COMMENT ON COLUMN SOSS.PLBX_INFO.plbx_nm IS '지구대명';
COMMENT ON COLUMN SOSS.PLBX_INFO.plbx_adrs IS '지구대주소';
COMMENT ON COLUMN SOSS.PLBX_INFO.plst_nm IS '경찰서명';
COMMENT ON COLUMN SOSS.PLBX_INFO.gu_cd IS '구코드';
COMMENT ON COLUMN SOSS.PLBX_INFO.la IS '위도';
COMMENT ON COLUMN SOSS.PLBX_INFO.lo IS '경도';